# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/mmc-wy/深圳学习资料/clion/clion-2018.2.5/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/mmc-wy/深圳学习资料/clion/clion-2018.2.5/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mmc-wy/mmc_onboard

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mmc-wy/mmc_onboard

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/mmc-wy/深圳学习资料/clion/clion-2018.2.5/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/mmc-wy/深圳学习资料/clion/clion-2018.2.5/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/mmc-wy/深圳学习资料/clion/clion-2018.2.5/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/mmc-wy/深圳学习资料/clion/clion-2018.2.5/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/mmc-wy/深圳学习资料/clion/clion-2018.2.5/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/mmc-wy/深圳学习资料/clion/clion-2018.2.5/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/mmc-wy/深圳学习资料/clion/clion-2018.2.5/bin/cmake/linux/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/mmc-wy/深圳学习资料/clion/clion-2018.2.5/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mmc-wy/mmc_onboard/CMakeFiles /home/mmc-wy/mmc_onboard/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mmc-wy/mmc_onboard/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tx2

# Build rule for target.
tx2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tx2
.PHONY : tx2

# fast build rule for target.
tx2/fast:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/build
.PHONY : tx2/fast

#=============================================================================
# Target rules for targets named test_cv_nanogui

# Build rule for target.
test_cv_nanogui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cv_nanogui
.PHONY : test_cv_nanogui

# fast build rule for target.
test_cv_nanogui/fast:
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/build
.PHONY : test_cv_nanogui/fast

#=============================================================================
# Target rules for targets named test_gst_opencv

# Build rule for target.
test_gst_opencv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_gst_opencv
.PHONY : test_gst_opencv

# fast build rule for target.
test_gst_opencv/fast:
	$(MAKE) -f CMakeFiles/test_gst_opencv.dir/build.make CMakeFiles/test_gst_opencv.dir/build
.PHONY : test_gst_opencv/fast

#=============================================================================
# Target rules for targets named libuavcan_dsdlc

# Build rule for target.
libuavcan_dsdlc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libuavcan_dsdlc
.PHONY : libuavcan_dsdlc

# fast build rule for target.
libuavcan_dsdlc/fast:
	$(MAKE) -f modules/libuavcan/libuavcan/CMakeFiles/libuavcan_dsdlc.dir/build.make modules/libuavcan/libuavcan/CMakeFiles/libuavcan_dsdlc.dir/build
.PHONY : libuavcan_dsdlc/fast

#=============================================================================
# Target rules for targets named uavcan_cpp03

# Build rule for target.
uavcan_cpp03: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uavcan_cpp03
.PHONY : uavcan_cpp03

# fast build rule for target.
uavcan_cpp03/fast:
	$(MAKE) -f modules/libuavcan/libuavcan/CMakeFiles/uavcan_cpp03.dir/build.make modules/libuavcan/libuavcan/CMakeFiles/uavcan_cpp03.dir/build
.PHONY : uavcan_cpp03/fast

#=============================================================================
# Target rules for targets named uavcan

# Build rule for target.
uavcan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uavcan
.PHONY : uavcan

# fast build rule for target.
uavcan/fast:
	$(MAKE) -f modules/libuavcan/libuavcan/CMakeFiles/uavcan.dir/build.make modules/libuavcan/libuavcan/CMakeFiles/uavcan.dir/build
.PHONY : uavcan/fast

#=============================================================================
# Target rules for targets named uavcan_optim

# Build rule for target.
uavcan_optim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uavcan_optim
.PHONY : uavcan_optim

# fast build rule for target.
uavcan_optim/fast:
	$(MAKE) -f modules/libuavcan/libuavcan/CMakeFiles/uavcan_optim.dir/build.make modules/libuavcan/libuavcan/CMakeFiles/uavcan_optim.dir/build
.PHONY : uavcan_optim/fast

#=============================================================================
# Target rules for targets named uavcan_dynamic_node_id_server

# Build rule for target.
uavcan_dynamic_node_id_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uavcan_dynamic_node_id_server
.PHONY : uavcan_dynamic_node_id_server

# fast build rule for target.
uavcan_dynamic_node_id_server/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/uavcan_dynamic_node_id_server.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/uavcan_dynamic_node_id_server.dir/build
.PHONY : uavcan_dynamic_node_id_server/fast

#=============================================================================
# Target rules for targets named uavcan_nodetool

# Build rule for target.
uavcan_nodetool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uavcan_nodetool
.PHONY : uavcan_nodetool

# fast build rule for target.
uavcan_nodetool/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/uavcan_nodetool.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/uavcan_nodetool.dir/build
.PHONY : uavcan_nodetool/fast

#=============================================================================
# Target rules for targets named test_time_sync

# Build rule for target.
test_time_sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_time_sync
.PHONY : test_time_sync

# fast build rule for target.
test_time_sync/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_time_sync.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_time_sync.dir/build
.PHONY : test_time_sync/fast

#=============================================================================
# Target rules for targets named test_file_server

# Build rule for target.
test_file_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_file_server
.PHONY : test_file_server

# fast build rule for target.
test_file_server/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_file_server.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_file_server.dir/build
.PHONY : test_file_server/fast

#=============================================================================
# Target rules for targets named test_node

# Build rule for target.
test_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_node
.PHONY : test_node

# fast build rule for target.
test_node/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_node.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_node.dir/build
.PHONY : test_node/fast

#=============================================================================
# Target rules for targets named uavcan_monitor

# Build rule for target.
uavcan_monitor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uavcan_monitor
.PHONY : uavcan_monitor

# fast build rule for target.
uavcan_monitor/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/uavcan_monitor.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/uavcan_monitor.dir/build
.PHONY : uavcan_monitor/fast

#=============================================================================
# Target rules for targets named test_clock

# Build rule for target.
test_clock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_clock
.PHONY : test_clock

# fast build rule for target.
test_clock/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_clock.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_clock.dir/build
.PHONY : test_clock/fast

#=============================================================================
# Target rules for targets named test_posix

# Build rule for target.
test_posix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_posix
.PHONY : test_posix

# fast build rule for target.
test_posix/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_posix.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_posix.dir/build
.PHONY : test_posix/fast

#=============================================================================
# Target rules for targets named test_system_utils

# Build rule for target.
test_system_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_system_utils
.PHONY : test_system_utils

# fast build rule for target.
test_system_utils/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_system_utils.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_system_utils.dir/build
.PHONY : test_system_utils/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_socket.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

#=============================================================================
# Target rules for targets named test_dynamic_node_id_client

# Build rule for target.
test_dynamic_node_id_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_dynamic_node_id_client
.PHONY : test_dynamic_node_id_client

# fast build rule for target.
test_dynamic_node_id_client/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_dynamic_node_id_client.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_dynamic_node_id_client.dir/build
.PHONY : test_dynamic_node_id_client/fast

#=============================================================================
# Target rules for targets named test_multithreading

# Build rule for target.
test_multithreading: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_multithreading
.PHONY : test_multithreading

# fast build rule for target.
test_multithreading/fast:
	$(MAKE) -f modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_multithreading.dir/build.make modules/libuavcan/libuavcan_drivers/linux/CMakeFiles/test_multithreading.dir/build
.PHONY : test_multithreading/fast

#=============================================================================
# Target rules for targets named example2

# Build rule for target.
example2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example2
.PHONY : example2

# fast build rule for target.
example2/fast:
	$(MAKE) -f modules/nanogui/CMakeFiles/example2.dir/build.make modules/nanogui/CMakeFiles/example2.dir/build
.PHONY : example2/fast

#=============================================================================
# Target rules for targets named example1

# Build rule for target.
example1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example1
.PHONY : example1

# fast build rule for target.
example1/fast:
	$(MAKE) -f modules/nanogui/CMakeFiles/example1.dir/build.make modules/nanogui/CMakeFiles/example1.dir/build
.PHONY : example1/fast

#=============================================================================
# Target rules for targets named nanogui-obj

# Build rule for target.
nanogui-obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nanogui-obj
.PHONY : nanogui-obj

# fast build rule for target.
nanogui-obj/fast:
	$(MAKE) -f modules/nanogui/CMakeFiles/nanogui-obj.dir/build.make modules/nanogui/CMakeFiles/nanogui-obj.dir/build
.PHONY : nanogui-obj/fast

#=============================================================================
# Target rules for targets named example3

# Build rule for target.
example3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example3
.PHONY : example3

# fast build rule for target.
example3/fast:
	$(MAKE) -f modules/nanogui/CMakeFiles/example3.dir/build.make modules/nanogui/CMakeFiles/example3.dir/build
.PHONY : example3/fast

#=============================================================================
# Target rules for targets named nanogui

# Build rule for target.
nanogui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nanogui
.PHONY : nanogui

# fast build rule for target.
nanogui/fast:
	$(MAKE) -f modules/nanogui/CMakeFiles/nanogui.dir/build.make modules/nanogui/CMakeFiles/nanogui.dir/build
.PHONY : nanogui/fast

#=============================================================================
# Target rules for targets named example_icons

# Build rule for target.
example_icons: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_icons
.PHONY : example_icons

# fast build rule for target.
example_icons/fast:
	$(MAKE) -f modules/nanogui/CMakeFiles/example_icons.dir/build.make modules/nanogui/CMakeFiles/example_icons.dir/build
.PHONY : example_icons/fast

#=============================================================================
# Target rules for targets named example4

# Build rule for target.
example4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example4
.PHONY : example4

# fast build rule for target.
example4/fast:
	$(MAKE) -f modules/nanogui/CMakeFiles/example4.dir/build.make modules/nanogui/CMakeFiles/example4.dir/build
.PHONY : example4/fast

#=============================================================================
# Target rules for targets named glfw_objects

# Build rule for target.
glfw_objects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw_objects
.PHONY : glfw_objects

# fast build rule for target.
glfw_objects/fast:
	$(MAKE) -f modules/nanogui/ext_build/glfw/src/CMakeFiles/glfw_objects.dir/build.make modules/nanogui/ext_build/glfw/src/CMakeFiles/glfw_objects.dir/build
.PHONY : glfw_objects/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f modules/nanogui/ext_build/glfw/src/CMakeFiles/glfw.dir/build.make modules/nanogui/ext_build/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named embed-resource

# Build rule for target.
embed-resource: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 embed-resource
.PHONY : embed-resource

# fast build rule for target.
embed-resource/fast:
	$(MAKE) -f modules/embed-resource/CMakeFiles/embed-resource.dir/build.make modules/embed-resource/CMakeFiles/embed-resource.dir/build
.PHONY : embed-resource/fast

modules/glad/src/glad.o: modules/glad/src/glad.c.o

.PHONY : modules/glad/src/glad.o

# target to build an object file
modules/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/modules/glad/src/glad.c.o
.PHONY : modules/glad/src/glad.c.o

modules/glad/src/glad.i: modules/glad/src/glad.c.i

.PHONY : modules/glad/src/glad.i

# target to preprocess a source file
modules/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/modules/glad/src/glad.c.i
.PHONY : modules/glad/src/glad.c.i

modules/glad/src/glad.s: modules/glad/src/glad.c.s

.PHONY : modules/glad/src/glad.s

# target to generate assembly for a file
modules/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/modules/glad/src/glad.c.s
.PHONY : modules/glad/src/glad.c.s

src/Calc/UavcanNode/UavcanNode.o: src/Calc/UavcanNode/UavcanNode.cpp.o

.PHONY : src/Calc/UavcanNode/UavcanNode.o

# target to build an object file
src/Calc/UavcanNode/UavcanNode.cpp.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/Calc/UavcanNode/UavcanNode.cpp.o
.PHONY : src/Calc/UavcanNode/UavcanNode.cpp.o

src/Calc/UavcanNode/UavcanNode.i: src/Calc/UavcanNode/UavcanNode.cpp.i

.PHONY : src/Calc/UavcanNode/UavcanNode.i

# target to preprocess a source file
src/Calc/UavcanNode/UavcanNode.cpp.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/Calc/UavcanNode/UavcanNode.cpp.i
.PHONY : src/Calc/UavcanNode/UavcanNode.cpp.i

src/Calc/UavcanNode/UavcanNode.s: src/Calc/UavcanNode/UavcanNode.cpp.s

.PHONY : src/Calc/UavcanNode/UavcanNode.s

# target to generate assembly for a file
src/Calc/UavcanNode/UavcanNode.cpp.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/Calc/UavcanNode/UavcanNode.cpp.s
.PHONY : src/Calc/UavcanNode/UavcanNode.cpp.s

src/Calc/VideoProcess/VideoProcess.o: src/Calc/VideoProcess/VideoProcess.cpp.o

.PHONY : src/Calc/VideoProcess/VideoProcess.o

# target to build an object file
src/Calc/VideoProcess/VideoProcess.cpp.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/Calc/VideoProcess/VideoProcess.cpp.o
.PHONY : src/Calc/VideoProcess/VideoProcess.cpp.o

src/Calc/VideoProcess/VideoProcess.i: src/Calc/VideoProcess/VideoProcess.cpp.i

.PHONY : src/Calc/VideoProcess/VideoProcess.i

# target to preprocess a source file
src/Calc/VideoProcess/VideoProcess.cpp.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/Calc/VideoProcess/VideoProcess.cpp.i
.PHONY : src/Calc/VideoProcess/VideoProcess.cpp.i

src/Calc/VideoProcess/VideoProcess.s: src/Calc/VideoProcess/VideoProcess.cpp.s

.PHONY : src/Calc/VideoProcess/VideoProcess.s

# target to generate assembly for a file
src/Calc/VideoProcess/VideoProcess.cpp.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/Calc/VideoProcess/VideoProcess.cpp.s
.PHONY : src/Calc/VideoProcess/VideoProcess.cpp.s

src/GUI/Interaction/arcball.o: src/GUI/Interaction/arcball.cpp.o

.PHONY : src/GUI/Interaction/arcball.o

# target to build an object file
src/GUI/Interaction/arcball.cpp.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/Interaction/arcball.cpp.o
.PHONY : src/GUI/Interaction/arcball.cpp.o

src/GUI/Interaction/arcball.i: src/GUI/Interaction/arcball.cpp.i

.PHONY : src/GUI/Interaction/arcball.i

# target to preprocess a source file
src/GUI/Interaction/arcball.cpp.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/Interaction/arcball.cpp.i
.PHONY : src/GUI/Interaction/arcball.cpp.i

src/GUI/Interaction/arcball.s: src/GUI/Interaction/arcball.cpp.s

.PHONY : src/GUI/Interaction/arcball.s

# target to generate assembly for a file
src/GUI/Interaction/arcball.cpp.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/Interaction/arcball.cpp.s
.PHONY : src/GUI/Interaction/arcball.cpp.s

src/GUI/Interaction/pan.o: src/GUI/Interaction/pan.cpp.o

.PHONY : src/GUI/Interaction/pan.o

# target to build an object file
src/GUI/Interaction/pan.cpp.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/Interaction/pan.cpp.o
.PHONY : src/GUI/Interaction/pan.cpp.o

src/GUI/Interaction/pan.i: src/GUI/Interaction/pan.cpp.i

.PHONY : src/GUI/Interaction/pan.i

# target to preprocess a source file
src/GUI/Interaction/pan.cpp.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/Interaction/pan.cpp.i
.PHONY : src/GUI/Interaction/pan.cpp.i

src/GUI/Interaction/pan.s: src/GUI/Interaction/pan.cpp.s

.PHONY : src/GUI/Interaction/pan.s

# target to generate assembly for a file
src/GUI/Interaction/pan.cpp.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/Interaction/pan.cpp.s
.PHONY : src/GUI/Interaction/pan.cpp.s

src/GUI/Interaction/zoom.o: src/GUI/Interaction/zoom.cpp.o

.PHONY : src/GUI/Interaction/zoom.o

# target to build an object file
src/GUI/Interaction/zoom.cpp.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/Interaction/zoom.cpp.o
.PHONY : src/GUI/Interaction/zoom.cpp.o

src/GUI/Interaction/zoom.i: src/GUI/Interaction/zoom.cpp.i

.PHONY : src/GUI/Interaction/zoom.i

# target to preprocess a source file
src/GUI/Interaction/zoom.cpp.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/Interaction/zoom.cpp.i
.PHONY : src/GUI/Interaction/zoom.cpp.i

src/GUI/Interaction/zoom.s: src/GUI/Interaction/zoom.cpp.s

.PHONY : src/GUI/Interaction/zoom.s

# target to generate assembly for a file
src/GUI/Interaction/zoom.cpp.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/Interaction/zoom.cpp.s
.PHONY : src/GUI/Interaction/zoom.cpp.s

src/GUI/application.o: src/GUI/application.cpp.o

.PHONY : src/GUI/application.o

# target to build an object file
src/GUI/application.cpp.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/application.cpp.o
.PHONY : src/GUI/application.cpp.o

src/GUI/application.i: src/GUI/application.cpp.i

.PHONY : src/GUI/application.i

# target to preprocess a source file
src/GUI/application.cpp.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/application.cpp.i
.PHONY : src/GUI/application.cpp.i

src/GUI/application.s: src/GUI/application.cpp.s

.PHONY : src/GUI/application.s

# target to generate assembly for a file
src/GUI/application.cpp.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/application.cpp.s
.PHONY : src/GUI/application.cpp.s

src/GUI/openglcanvas.o: src/GUI/openglcanvas.cpp.o

.PHONY : src/GUI/openglcanvas.o

# target to build an object file
src/GUI/openglcanvas.cpp.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/openglcanvas.cpp.o
.PHONY : src/GUI/openglcanvas.cpp.o

src/GUI/openglcanvas.i: src/GUI/openglcanvas.cpp.i

.PHONY : src/GUI/openglcanvas.i

# target to preprocess a source file
src/GUI/openglcanvas.cpp.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/openglcanvas.cpp.i
.PHONY : src/GUI/openglcanvas.cpp.i

src/GUI/openglcanvas.s: src/GUI/openglcanvas.cpp.s

.PHONY : src/GUI/openglcanvas.s

# target to generate assembly for a file
src/GUI/openglcanvas.cpp.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/openglcanvas.cpp.s
.PHONY : src/GUI/openglcanvas.cpp.s

src/GUI/shader/basicShader.fs.o: src/GUI/shader/basicShader.fs.c.o

.PHONY : src/GUI/shader/basicShader.fs.o

# target to build an object file
src/GUI/shader/basicShader.fs.c.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/basicShader.fs.c.o
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/basicShader.fs.c.o
.PHONY : src/GUI/shader/basicShader.fs.c.o

src/GUI/shader/basicShader.fs.i: src/GUI/shader/basicShader.fs.c.i

.PHONY : src/GUI/shader/basicShader.fs.i

# target to preprocess a source file
src/GUI/shader/basicShader.fs.c.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/basicShader.fs.c.i
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/basicShader.fs.c.i
.PHONY : src/GUI/shader/basicShader.fs.c.i

src/GUI/shader/basicShader.fs.s: src/GUI/shader/basicShader.fs.c.s

.PHONY : src/GUI/shader/basicShader.fs.s

# target to generate assembly for a file
src/GUI/shader/basicShader.fs.c.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/basicShader.fs.c.s
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/basicShader.fs.c.s
.PHONY : src/GUI/shader/basicShader.fs.c.s

src/GUI/shader/basicShader.vs.o: src/GUI/shader/basicShader.vs.c.o

.PHONY : src/GUI/shader/basicShader.vs.o

# target to build an object file
src/GUI/shader/basicShader.vs.c.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/basicShader.vs.c.o
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/basicShader.vs.c.o
.PHONY : src/GUI/shader/basicShader.vs.c.o

src/GUI/shader/basicShader.vs.i: src/GUI/shader/basicShader.vs.c.i

.PHONY : src/GUI/shader/basicShader.vs.i

# target to preprocess a source file
src/GUI/shader/basicShader.vs.c.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/basicShader.vs.c.i
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/basicShader.vs.c.i
.PHONY : src/GUI/shader/basicShader.vs.c.i

src/GUI/shader/basicShader.vs.s: src/GUI/shader/basicShader.vs.c.s

.PHONY : src/GUI/shader/basicShader.vs.s

# target to generate assembly for a file
src/GUI/shader/basicShader.vs.c.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/basicShader.vs.c.s
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/basicShader.vs.c.s
.PHONY : src/GUI/shader/basicShader.vs.c.s

src/GUI/shader/frag.glsl.o: src/GUI/shader/frag.glsl.c.o

.PHONY : src/GUI/shader/frag.glsl.o

# target to build an object file
src/GUI/shader/frag.glsl.c.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/frag.glsl.c.o
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/frag.glsl.c.o
.PHONY : src/GUI/shader/frag.glsl.c.o

src/GUI/shader/frag.glsl.i: src/GUI/shader/frag.glsl.c.i

.PHONY : src/GUI/shader/frag.glsl.i

# target to preprocess a source file
src/GUI/shader/frag.glsl.c.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/frag.glsl.c.i
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/frag.glsl.c.i
.PHONY : src/GUI/shader/frag.glsl.c.i

src/GUI/shader/frag.glsl.s: src/GUI/shader/frag.glsl.c.s

.PHONY : src/GUI/shader/frag.glsl.s

# target to generate assembly for a file
src/GUI/shader/frag.glsl.c.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/frag.glsl.c.s
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/frag.glsl.c.s
.PHONY : src/GUI/shader/frag.glsl.c.s

src/GUI/shader/vert.glsl.o: src/GUI/shader/vert.glsl.c.o

.PHONY : src/GUI/shader/vert.glsl.o

# target to build an object file
src/GUI/shader/vert.glsl.c.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/vert.glsl.c.o
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/vert.glsl.c.o
.PHONY : src/GUI/shader/vert.glsl.c.o

src/GUI/shader/vert.glsl.i: src/GUI/shader/vert.glsl.c.i

.PHONY : src/GUI/shader/vert.glsl.i

# target to preprocess a source file
src/GUI/shader/vert.glsl.c.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/vert.glsl.c.i
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/vert.glsl.c.i
.PHONY : src/GUI/shader/vert.glsl.c.i

src/GUI/shader/vert.glsl.s: src/GUI/shader/vert.glsl.c.s

.PHONY : src/GUI/shader/vert.glsl.s

# target to generate assembly for a file
src/GUI/shader/vert.glsl.c.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/GUI/shader/vert.glsl.c.s
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/src/GUI/shader/vert.glsl.c.s
.PHONY : src/GUI/shader/vert.glsl.c.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/tx2.dir/build.make CMakeFiles/tx2.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test_cv_nanogui.o: test_cv_nanogui.cpp.o

.PHONY : test_cv_nanogui.o

# target to build an object file
test_cv_nanogui.cpp.o:
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/test_cv_nanogui.cpp.o
.PHONY : test_cv_nanogui.cpp.o

test_cv_nanogui.i: test_cv_nanogui.cpp.i

.PHONY : test_cv_nanogui.i

# target to preprocess a source file
test_cv_nanogui.cpp.i:
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/test_cv_nanogui.cpp.i
.PHONY : test_cv_nanogui.cpp.i

test_cv_nanogui.s: test_cv_nanogui.cpp.s

.PHONY : test_cv_nanogui.s

# target to generate assembly for a file
test_cv_nanogui.cpp.s:
	$(MAKE) -f CMakeFiles/test_cv_nanogui.dir/build.make CMakeFiles/test_cv_nanogui.dir/test_cv_nanogui.cpp.s
.PHONY : test_cv_nanogui.cpp.s

test_gst_opencv.o: test_gst_opencv.cpp.o

.PHONY : test_gst_opencv.o

# target to build an object file
test_gst_opencv.cpp.o:
	$(MAKE) -f CMakeFiles/test_gst_opencv.dir/build.make CMakeFiles/test_gst_opencv.dir/test_gst_opencv.cpp.o
.PHONY : test_gst_opencv.cpp.o

test_gst_opencv.i: test_gst_opencv.cpp.i

.PHONY : test_gst_opencv.i

# target to preprocess a source file
test_gst_opencv.cpp.i:
	$(MAKE) -f CMakeFiles/test_gst_opencv.dir/build.make CMakeFiles/test_gst_opencv.dir/test_gst_opencv.cpp.i
.PHONY : test_gst_opencv.cpp.i

test_gst_opencv.s: test_gst_opencv.cpp.s

.PHONY : test_gst_opencv.s

# target to generate assembly for a file
test_gst_opencv.cpp.s:
	$(MAKE) -f CMakeFiles/test_gst_opencv.dir/build.make CMakeFiles/test_gst_opencv.dir/test_gst_opencv.cpp.s
.PHONY : test_gst_opencv.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... tx2"
	@echo "... edit_cache"
	@echo "... test_cv_nanogui"
	@echo "... test_gst_opencv"
	@echo "... libuavcan_dsdlc"
	@echo "... uavcan_cpp03"
	@echo "... uavcan"
	@echo "... uavcan_optim"
	@echo "... uavcan_dynamic_node_id_server"
	@echo "... uavcan_nodetool"
	@echo "... test_time_sync"
	@echo "... test_file_server"
	@echo "... test_node"
	@echo "... uavcan_monitor"
	@echo "... test_clock"
	@echo "... test_posix"
	@echo "... test_system_utils"
	@echo "... test_socket"
	@echo "... test_dynamic_node_id_client"
	@echo "... test_multithreading"
	@echo "... example2"
	@echo "... example1"
	@echo "... nanogui-obj"
	@echo "... example3"
	@echo "... nanogui"
	@echo "... example_icons"
	@echo "... example4"
	@echo "... glfw_objects"
	@echo "... glfw"
	@echo "... embed-resource"
	@echo "... modules/glad/src/glad.o"
	@echo "... modules/glad/src/glad.i"
	@echo "... modules/glad/src/glad.s"
	@echo "... src/Calc/UavcanNode/UavcanNode.o"
	@echo "... src/Calc/UavcanNode/UavcanNode.i"
	@echo "... src/Calc/UavcanNode/UavcanNode.s"
	@echo "... src/Calc/VideoProcess/VideoProcess.o"
	@echo "... src/Calc/VideoProcess/VideoProcess.i"
	@echo "... src/Calc/VideoProcess/VideoProcess.s"
	@echo "... src/GUI/Interaction/arcball.o"
	@echo "... src/GUI/Interaction/arcball.i"
	@echo "... src/GUI/Interaction/arcball.s"
	@echo "... src/GUI/Interaction/pan.o"
	@echo "... src/GUI/Interaction/pan.i"
	@echo "... src/GUI/Interaction/pan.s"
	@echo "... src/GUI/Interaction/zoom.o"
	@echo "... src/GUI/Interaction/zoom.i"
	@echo "... src/GUI/Interaction/zoom.s"
	@echo "... src/GUI/application.o"
	@echo "... src/GUI/application.i"
	@echo "... src/GUI/application.s"
	@echo "... src/GUI/openglcanvas.o"
	@echo "... src/GUI/openglcanvas.i"
	@echo "... src/GUI/openglcanvas.s"
	@echo "... src/GUI/shader/basicShader.fs.o"
	@echo "... src/GUI/shader/basicShader.fs.i"
	@echo "... src/GUI/shader/basicShader.fs.s"
	@echo "... src/GUI/shader/basicShader.vs.o"
	@echo "... src/GUI/shader/basicShader.vs.i"
	@echo "... src/GUI/shader/basicShader.vs.s"
	@echo "... src/GUI/shader/frag.glsl.o"
	@echo "... src/GUI/shader/frag.glsl.i"
	@echo "... src/GUI/shader/frag.glsl.s"
	@echo "... src/GUI/shader/vert.glsl.o"
	@echo "... src/GUI/shader/vert.glsl.i"
	@echo "... src/GUI/shader/vert.glsl.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test_cv_nanogui.o"
	@echo "... test_cv_nanogui.i"
	@echo "... test_cv_nanogui.s"
	@echo "... test_gst_opencv.o"
	@echo "... test_gst_opencv.i"
	@echo "... test_gst_opencv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

